name: Verdecraft
version: '${project.version}'
main: verdecraft.verdecraft.Verdecraft
api-version: 1.19
authors: [ Michal_Grocholski, Adam_Cherek, Barlomiej_Michalowski ]
description: Ecological oriented minecraft plugin.
commands:
  temp_check:
    description: Check temperature.
  temp_set:
    description: Set temperature.
    usage: /<command> <temperature>
  time_check:
    description: Check time.
  modi_set:
    description: Set modifier.
  modi_check:
    description: Check modifier.
  give_custom_items:
    description: Gives custom items.