name: Verdecraft
version: 'Alpha 0.1'
main: verdecraft.verdecraft.Verdecraft
api-version: 1.19
authors: [ Michal_Grocholski, Adam_Cherek, Barlomiej_Michalowski ]
description: Ecological oriented minecraft plugin.
commands:
  verde_temp_check:
    description: Check temperature.
  verde_temp_set:
    description: Set temperature.
    usage: /<command> <temperature>
  verde_time_check:
    description: Check time.
  verde_modi_set:
    description: Set modifier.
  verde_modi_check:
    description: Check modifier.
  verde_items:
    description: Gives VerdeCraft items.